# Generated by Django 4.2.5 on 2023-09-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPIApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='unit_price',
        ),
    ]
